name: action workflow

on: push

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: simple javascript action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: john
      - name: greeting time
        run: echo "${{ steps.greet.outputs.time}}"

      - name: list of files
        run: | 
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v2
      - name: list of files after checkout
        run: |
          pwd
          ls -a
        

