name: shell commands

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: eceho "Hello world" 
      - name: displaying node version 
        run: | 
          node -v 
          npm -v 

  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: present working directory
        run: pwd